version: "3"

services:
  greeter:
    container_name: greeter
    build:
      context: .
      dockerfile: ./apps/greeter/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - test_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  test_network:
    external: true